import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { repoRootFrom } from "./lib/index.mjs";
const root = repoRootFrom(import.meta.url);
const path = join(root, ".agents/dashboard/index.html");
if (!existsSync(path)) throw new Error("대시보드 HTML 파일이 없습니다");
const html = readFileSync(path, "utf8");
if (!html.includes("dashboard-data") || !html.includes("라비에벨 개발 현황") || !html.includes("blockers")) throw new Error("대시보드 계약이 누락되었습니다");
if (!html.includes("--blue:#0052ff") || !html.includes("Pretendard Variable")) throw new Error("디자인 시스템 토큰이 적용되지 않았습니다");
if (html.includes("sample-runs") || html.includes("sample data")) throw new Error("샘플 데이터 대체 화면이 감지되었습니다");
console.log("대시보드 스모크 검사를 통과했습니다");
