export const LATE_THRESHOLD_MINUTES = 10;

export const CHECKED_AT_DEVICE_TOLERANCE_MINUTES = 10;

export const CHECK_IN_WINDOW_LEAD_MINUTES = 60;

export const CHECK_IN_WINDOW_CLOSE_HOUR_KST = 18;

export const EXCUSE_DEADLINE_HOURS = 48;

export const COMMUNICATION_DELAY_MINUTES = 5;

export const EXCUSE_BODY_MAX_LENGTH = 200;
