export type EnforcedRule = {
  no: number;
  name: string;
  mechanism: "eslint" | "house" | "prettier" | "hook" | "pre-commit";
  ruleId: string | null;
  enforcedBy: string | null;
  test: string | null;
};

export const DOCUMENTED_LINT_RULE_COUNT = 43;

export const RULE_NUMBERS_NEVER_ASSIGNED = [6, 7, 8];

export const RULES: EnforcedRule[] = [
  {
    no: 1,
    name: "상대 경로 import 금지",
    mechanism: "eslint",
    ruleId: "no-restricted-imports",
    enforcedBy: null,
    test: "tests/lint/relativeImport.test.ts",
  },
  {
    no: 2,
    name: "FSD 역방향 import",
    mechanism: "eslint",
    ruleId: "no-restricted-imports",
    enforcedBy: null,
    test: "tests/lint/fsdLayerOrder.test.ts",
  },
  {
    no: 3,
    name: "같은 층 다른 슬라이스 import",
    mechanism: "house",
    ruleId: "house/no-cross-slice-import",
    enforcedBy: null,
    test: "tests/lint/fsdSliceBoundary.test.ts",
  },
  {
    no: 4,
    name: "하드코딩한 색과 크기",
    mechanism: "house",
    ruleId: "house/no-arbitrary-class-values",
    enforcedBy: null,
    test: "tests/lint/designTokenValues.test.ts",
  },
  {
    no: 4,
    name: "하드코딩한 색과 크기",
    mechanism: "house",
    ruleId: "house/no-color-literals",
    enforcedBy: null,
    test: "tests/lint/designTokenValues.test.ts",
  },
  {
    no: 5,
    name: "Tailwind 기본 팔레트 유틸리티",
    mechanism: "house",
    ruleId: "house/no-default-palette-class",
    enforcedBy: null,
    test: "tests/lint/tailwindDefaultPalette.test.ts",
  },
  {
    no: 9,
    name: ".tsx는 더미 UI",
    mechanism: "house",
    ruleId: "house/dumb-ui",
    enforcedBy: null,
    test: "tests/lint/tsxDumbUi.test.ts",
  },
  {
    no: 10,
    name: "집중 실행 표시",
    mechanism: "eslint",
    ruleId: "no-restricted-syntax",
    enforcedBy: null,
    test: "tests/lint/noFocusedTests.test.ts",
  },
  {
    no: 11,
    name: "import 순서",
    mechanism: "eslint",
    ruleId: "import/order",
    enforcedBy: null,
    test: "tests/lint/importOrder.test.ts",
  },
  {
    no: 12,
    name: "Tailwind 클래스 순서",
    mechanism: "prettier",
    ruleId: null,
    enforcedBy: "prettier.config.mjs",
    test: "tests/lint/formatCheck.test.ts",
  },
  {
    no: 13,
    name: "console",
    mechanism: "eslint",
    ruleId: "no-console",
    enforcedBy: null,
    test: "tests/lint/noConsole.test.ts",
  },
  {
    no: 14,
    name: "미사용 import와 import type",
    mechanism: "eslint",
    ruleId: "unused-imports/no-unused-imports",
    enforcedBy: null,
    test: "tests/lint/unusedImports.test.ts",
  },
  {
    no: 14,
    name: "미사용 import와 import type",
    mechanism: "eslint",
    ruleId: "@typescript-eslint/consistent-type-imports",
    enforcedBy: null,
    test: "tests/lint/unusedImports.test.ts",
  },
  {
    no: 15,
    name: "내보내는 함수마다 그것을 부르는 짝 테스트가 먼저 있어야 한다",
    mechanism: "hook",
    ruleId: null,
    enforcedBy: ".claude/hooks/tdd-guard-unit.py",
    test: ".claude/hooks/__tests__/tdd-guard.test.ts",
  },
  {
    no: 16,
    name: "화면과 라우트를 쓰기 전에 e2e 플로우가 있어야 한다",
    mechanism: "hook",
    ruleId: null,
    enforcedBy: ".claude/hooks/tdd-guard-e2e.py",
    test: ".claude/hooks/__tests__/tdd-guard.test.ts",
  },
  {
    no: 17,
    name: "시크릿과 .env는 커밋할 수 없다",
    mechanism: "pre-commit",
    ruleId: null,
    enforcedBy: ".githooks/pre-commit",
    test: "tests/lint/preCommit.test.ts",
  },
  {
    no: 18,
    name: "승인된 spec 없이 feat 브랜치에서 src/를 고칠 수 없다",
    mechanism: "hook",
    ruleId: null,
    enforcedBy: ".claude/hooks/spec-gate.py",
    test: ".claude/hooks/__tests__/spec-gate.test.ts",
  },
  {
    no: 19,
    name: "화면 파일의 시각 유틸리티",
    mechanism: "house",
    ruleId: "house/no-visual-utility-class",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noVisualUtilityClass.test.ts",
  },
  {
    no: 20,
    name: "Edge Function의 마운트 밖 import",
    mechanism: "house",
    ruleId: "house/no-edge-function-src-import",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noEdgeFunctionSrcImport.test.ts",
  },
  {
    no: 21,
    name: "Deno로 복사되는 폴더의 node: import",
    mechanism: "house",
    ruleId: "house/no-node-import-in-edge-shared",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noNodeImportInEdgeShared.test.ts",
  },
  {
    no: 22,
    name: "api 세그먼트 밖의 Supabase 패키지 import",
    mechanism: "house",
    ruleId: "house/supabase-package-in-api",
    enforcedBy: null,
    test: "eslint-rules/__tests__/supabasePackageInApi.test.ts",
  },
  {
    no: 23,
    name: "ui 세그먼트의 api import",
    mechanism: "house",
    ruleId: "house/no-api-import-in-ui",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noApiImportInUi.test.ts",
  },
  {
    no: 24,
    name: "ui 세그먼트의 services import",
    mechanism: "house",
    ruleId: "house/no-services-import-in-ui",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noServicesImportInUi.test.ts",
  },
  {
    no: 25,
    name: "services 세그먼트 밖의 Query·Mutation 훅",
    mechanism: "house",
    ruleId: "house/query-hook-in-services",
    enforcedBy: null,
    test: "eslint-rules/__tests__/queryHookInServices.test.ts",
  },
  {
    no: 26,
    name: "ui 세그먼트의 Supabase 클라이언트 실물",
    mechanism: "house",
    ruleId: "house/no-supabase-instance-in-ui",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noSupabaseInstanceInUi.test.ts",
  },
  {
    no: 27,
    name: "entities의 쓰기 훅",
    mechanism: "house",
    ruleId: "house/entities-read-only",
    enforcedBy: null,
    test: "eslint-rules/__tests__/entitiesReadOnly.test.ts",
  },
  {
    no: 28,
    name: "features의 읽기 service가 맞추는 도메인 수",
    mechanism: "house",
    ruleId: "house/features-query-composes",
    enforcedBy: null,
    test: "eslint-rules/__tests__/featuresQueryComposes.test.ts",
  },
  {
    no: 29,
    name: "설명 주석",
    mechanism: "house",
    ruleId: "house/no-explanatory-comment",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noExplanatoryComment.test.ts",
  },
  {
    no: 30,
    name: "hooks·services·stores 밖의 use* export",
    mechanism: "house",
    ruleId: "house/use-export-segment",
    enforcedBy: null,
    test: "eslint-rules/__tests__/useExportSegment.test.ts",
  },
  {
    no: 31,
    name: "stores 밖의 store·Context 공장",
    mechanism: "house",
    ruleId: "house/store-factory-in-stores",
    enforcedBy: null,
    test: "eslint-rules/__tests__/storeFactoryInStores.test.ts",
  },
  {
    no: 32,
    name: "policy·reducer 접미사의 통신·시계·난수",
    mechanism: "house",
    ruleId: "house/pure-policy",
    enforcedBy: null,
    test: "eslint-rules/__tests__/purePolicy.test.ts",
  },
  {
    no: 33,
    name: "캐시 키 배열 리터럴",
    mechanism: "house",
    ruleId: "house/query-key-factory",
    enforcedBy: null,
    test: "eslint-rules/__tests__/queryKeyFactory.test.ts",
  },
  {
    no: 34,
    name: "consts 밖에서 내보내는 대문자 스네이크 이름",
    mechanism: "house",
    ruleId: "house/consts-segment",
    enforcedBy: null,
    test: "eslint-rules/__tests__/constsSegment.test.ts",
  },
  {
    no: 35,
    name: "config 밖의 환경값 읽기",
    mechanism: "house",
    ruleId: "house/env-in-config",
    enforcedBy: null,
    test: "eslint-rules/__tests__/envInConfig.test.ts",
  },
  {
    no: 36,
    name: "lib·ui·hooks·config 밖의 네이티브 SDK",
    mechanism: "house",
    ruleId: "house/native-sdk-segment",
    enforcedBy: null,
    test: "eslint-rules/__tests__/nativeSdkSegment.test.ts",
  },
  {
    no: 37,
    name: "api 밖의 `.dto.ts` import",
    mechanism: "house",
    ruleId: "house/dto-segment",
    enforcedBy: null,
    test: "eslint-rules/__tests__/dtoSegment.test.ts",
  },
  {
    no: 38,
    name: "api 밖의 snake_case 필드 선언",
    mechanism: "house",
    ruleId: "house/no-snake-case-field",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noSnakeCaseField.test.ts",
  },
  {
    no: 39,
    name: "ui의 model·utils 값 import",
    mechanism: "house",
    ruleId: "house/ui-value-import",
    enforcedBy: null,
    test: "eslint-rules/__tests__/uiValueImport.test.ts",
  },
  {
    no: 40,
    name: "ui의 라우팅 훅",
    mechanism: "house",
    ruleId: "house/ui-no-router",
    enforcedBy: null,
    test: "eslint-rules/__tests__/uiNoRouter.test.ts",
  },
  {
    no: 41,
    name: "기다리지 않는 쓰기 뒤처리",
    mechanism: "house",
    ruleId: "house/mutation-settle-shape",
    enforcedBy: null,
    test: "eslint-rules/__tests__/mutationSettleShape.test.ts",
  },
  {
    no: 42,
    name: "shared 밖의 재수출",
    mechanism: "house",
    ruleId: "house/no-layer-reexport",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noLayerReexport.test.ts",
  },
  {
    no: 43,
    name: "복사된 통신 실패 문안",
    mechanism: "house",
    ruleId: "house/no-duplicate-failure-copy",
    enforcedBy: null,
    test: "eslint-rules/__tests__/noDuplicateFailureCopy.test.ts",
  },
];

export const ENFORCED_RULE_COUNT = Math.max(
  ...RULES.map((rule) => rule.no),
  ...RULE_NUMBERS_NEVER_ASSIGNED,
);
