export const ERROR_CODES = [
  "already_approved",
  "already_confirmed",
  "already_decided",
  "already_done",
  "already_exists",
  "already_open",
  "already_requested",
  "already_submitted",
  "bad_hours",
  "bad_radius",
  "date_past",
  "deadline_past",
  "invalid_qr",
  "invalid_reason",
  "month_over",
  "no_schedule",
  "not_allowed",
  "not_open",
  "too_early",
  "too_far",
  "window_closed",
] as const;
